In [2]:
import numpy as np

In [3]:
from keras.models import Sequential
from keras.layers import Dense

# Suppose you have a dataset with 10 features (input_dim=10)
model = Sequential()
model.add(Dense(32, input_dim=10, activation='relu'))
model.summary()




Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                352       
                                                                 
Total params: 352 (1.38 KB)
Trainable params: 352 (1.38 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [4]:
from keras.models import Sequential
from keras.layers import LSTM

# Suppose you have a time series dataset with 100 time steps and 5 features
model = Sequential()
model.add(LSTM(64, input_shape=(100, 5)))
model.summary()


Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 64)                17920     
                                                                 
Total params: 17920 (70.00 KB)
Trainable params: 17920 (70.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [6]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x[2]

2

In [8]:
x.shape = (2, 5)

In [9]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
x[1, 3]

8

In [36]:
y=np.linspace(433,1)
y

array([433.        , 424.18367347, 415.36734694, 406.55102041,
       397.73469388, 388.91836735, 380.10204082, 371.28571429,
       362.46938776, 353.65306122, 344.83673469, 336.02040816,
       327.20408163, 318.3877551 , 309.57142857, 300.75510204,
       291.93877551, 283.12244898, 274.30612245, 265.48979592,
       256.67346939, 247.85714286, 239.04081633, 230.2244898 ,
       221.40816327, 212.59183673, 203.7755102 , 194.95918367,
       186.14285714, 177.32653061, 168.51020408, 159.69387755,
       150.87755102, 142.06122449, 133.24489796, 124.42857143,
       115.6122449 , 106.79591837,  97.97959184,  89.16326531,
        80.34693878,  71.53061224,  62.71428571,  53.89795918,
        45.08163265,  36.26530612,  27.44897959,  18.63265306,
         9.81632653,   1.        ])

In [33]:
# y
next_y = np.reshape(y, [ 433, 1])

ValueError: cannot reshape array of size 1 into shape (433,1)

In [20]:
next_y.shape

(1, 1, 433, 1)

In [30]:
next_y = np.reshape(y, [ 433, 2])

ValueError: cannot reshape array of size 50 into shape (433,2)

In [23]:
next_y.shape

(433, 1)